using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

#nullable enable

namespace ConsoleMVC.Generators;

[Generator]
public class ViewSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var viewFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".cvw", StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(viewFiles, static (ctx, file) =>
        {
            var text = file.GetText(ctx.CancellationToken);
            if (text == null) return;

            var content = text.ToString();
            var lines = content.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);

            string? modelType = null;
            var usings = new List<string>();
            var codeStartIndex = 0;

            // Parse directives (@model, @using) at the top of the file
            for (var i = 0; i < lines.Length; i++)
            {
                var trimmed = lines[i].Trim();

                if (string.IsNullOrWhiteSpace(trimmed))
                {
                    codeStartIndex = i + 1;
                    continue;
                }

                if (trimmed.StartsWith("@model "))
                {
                    modelType = trimmed.Substring("@model ".Length).Trim();
                    codeStartIndex = i + 1;
                    continue;
                }

                if (trimmed.StartsWith("@using "))
                {
                    usings.Add(trimmed.Substring("@using ".Length).Trim());
                    codeStartIndex = i + 1;
                    continue;
                }

                // First non-directive, non-empty line — code starts here
                codeStartIndex = i;
                break;
            }

            // Skip files without @model directive
            if (modelType == null) return;

            // Extract view name and controller name from file path
            // Expected path pattern: .../Views/{Controller}/{Action}View.cvw
            var fileName = Path.GetFileNameWithoutExtension(file.Path);
            var pathParts = file.Path.Replace('\\', '/').Split('/');

            string? controllerName = null;
            for (var i = 0; i < pathParts.Length - 1; i++)
            {
                if (string.Equals(pathParts[i], "Views", StringComparison.OrdinalIgnoreCase)
                    && i + 1 < pathParts.Length - 1)
                {
                    controllerName = pathParts[i + 1];
                    break;
                }
            }

            if (controllerName == null) return;

            // Build the view body code with proper indentation
            var codeLines = lines.Skip(codeStartIndex).ToArray();
            var codeBody = string.Join("\n",
                codeLines.Select(l => "        " + l));

            // Build using statements
            var usingBuilder = new StringBuilder();
            usingBuilder.AppendLine("using ConsoleMVC.Mvc;");
            foreach (var u in usings)
            {
                usingBuilder.AppendLine($"using {u};");
            }

            var source = $@"// <auto-generated>
// Generated by ConsoleMVC ViewEngine from {controllerName}/{fileName}.cvw
// Do not modify this file directly — edit the .cvw source instead.
// </auto-generated>
{usingBuilder}
namespace ConsoleMVC.Views.{controllerName}
{{
    public class {fileName} : ConsoleView<{modelType}>
    {{
        public override NavigationResult Render({modelType} Model)
        {{
{codeBody}
        }}
    }}
}}";

            ctx.AddSource($"{controllerName}_{fileName}.g.cs", source);
        });
    }
}
